import { Message } from "whatsapp-web.js";
import { promptTracker } from "../clients/prompt";
import { sydney } from "../clients/sydney";
import { config } from "../config";
import { getAvailableTones, react } from "../utils";

const AVAILABLE_TONES = getAvailableTones();

function truncateWithEllipsis(input: string, maxLength: number): string {
  if (input.length <= maxLength || maxLength < 4) {
    return input;
  }

  const halfLength = Math.floor((maxLength - 3) / 2);
  const start = input.substring(0, halfLength);
  const end = input.substring(input.length - halfLength);
  return `${start} ... ${end}`;
}

export async function handleCommand(
  message: Message,
  command: string,
  args?: string
) {
  const chat = await message.getChat();
  await chat.sendSeen();

  await react(message, "working");
  switch (command.toLowerCase()) {
    case "!ping":
      await message.reply("*pong!*");
      break;
    case "!reset":
      await sydney.conversationsCache.delete(chat.id._serialized);
      await message.reply("Conversation history reset.");
      break;
    case "!pending":
      const pendingPrompts = promptTracker.listPendingPrompts(chat);

      if (pendingPrompts.length === 0) {
        await message.reply("There are no pending prompts.");
        break;
      }

      const pendingTexts = pendingPrompts
        .map(
          ({ data }, number) => `--- Prompt ${number} ---\n${data.text}\n---`
        )
        .join("\n\n");
      const pendingTextsTruncated = truncateWithEllipsis(pendingTexts, 60);

      await message.reply(
        `These are the pending prompts:\n\n${pendingTextsTruncated}`
      );
      break;
    case "!tone":
      if (!args)
        await message.reply(
          `Current tone: *${config.toneStyle}*.\n\n` +
            "To set a different tone, pass it as a parameter to the *!tone* command (eg.: *!tone precise*).\n\n" +
            AVAILABLE_TONES
        );
      else {
        const tone = args.trim().toLowerCase();
        const isValidTone = config.VALID_TONES.includes(
          tone as (typeof config.VALID_TONES)[number]
        );

        if (isValidTone) {
          config.toneStyle = tone as typeof config.toneStyle;
          await message.reply(`Tone set to: *${config.toneStyle}*`);
        } else {
          await message.reply(
            `Tone *${tone}* is invalid.\n\n` + AVAILABLE_TONES
          );
        }
      }
      break;
    case "!help":
      // this help message was generated by Sydney
      await message.reply(
        "Ini Beberapa Perintah Yang Tersedia Yah:\n\n" +
          "👉 *!help* Menampilkan pesan bantuan yang berisi daftar perintah yang tersedia.\n" +
          "👉 *!ping* Memberi tahu apakah bot masih berjalan atau tidak.\n" +
          "👉 *!tone (argumen)* Memungkinkan Anda memeriksa nada (tone) saat ini yang digunakan oleh Sydney dalam merespons.Argumen dapat berupa creative (Jawaban kreatif), balanced (seimbang antara kreatif dan ketepatan) , atau precise (ketepatan jawaban). Jika Anda tidak memberikan argumen, bot akan membalas dengan nada saat ini yang dikonfigurasi dan opsi yang tersedia. \n" +
          "👉 *!pending* Memberikan daftar permintaan yang Anda buat dan masih menunggu balasan dari Sydney.\n" +
          "👉 *!status* Memberikan daftar status yang digunakan di chatbot ini.\n" +
          "👉 *!reset* Menghapus riwayat percakapan saat ini\n." +
          "👉 Bot ini bisa digunakan secara pribadi ataupun di group chat, jika ingin menggunakan di group chat kamu harus menandai bot ini. example : *@Bot Halo*"
      );
      break;
      case "!status":
        await message.reply(
          "1. 🔁 Tanda ini artinya pesan kamu *Dalam Antrian*\n" +
          "2. ⚙️ Tanda ini artinya pesan kamu *Sedang Dibalas*\n" +
          "3. ✅ Tanda ini artinya pesan kamu *Telah Dibalas*\n" +
          "4. ⚠️ Tanda ini artinya pesan kamu *Error / Terjadi Kesalahan*\n" 
        )
        break;
    default:
      await message.reply(`Command *${command}* unknown.`);
      break;
  }

  await react(message, "done");
}
